' Gambas module file

Public Societe As String
Public VersionT As String
Public son As Integer
Public Musique As String = "son/warning.ogg"
Public Caisse As Boolean
Public Proform As String = Settings["/Coul/Prf"]
Public Commande As String = Settings["/Coul/Cmde"]
Public Devis As String = Settings["/Coul/Devis"]
Public Devis2 As String = Settings["/Coul/Devis2"]
Public Bon As String = Settings["/Coul/Bl"]
Public Facture As String = Settings["/Coul/Facts"]
Public Epuises As String = Settings["/Coul/Eps"]
Public Stockes As String = Settings["/Coul/Stk"]
Public Nstockes As String = Settings["/Coul/Nstk"]
Public Suspendus As String = Settings["/Coul/Spd"]
Private Lig2 As String[]
Private Fontes As String
Private hpb As ProgressBar
Public R As Integer = 255
Public G As Integer = 255
Public B As Integer = 255
Public R2 As Integer
Public G2 As Integer
Public B2 As Integer
Public Motdepasse As String
Private hlb As Label

Public Sub Main()

  Try Societe = Settings["/Soc"]
  Try Son = Settings["/son"]
  If Son Then Music.Load(Musique)
  Try VersionT = Settings["/dbase/Version"]
  If Error Or If IsNull(Settings["/Coul" & "/Fnets"]) Then
    Settings["/Coul" & "/Fnets"] = "Background: &HDDDDDD&; "
    Settings["/Coul" & "/Btns"] = "Background: &HBDBDBD&; "
    Settings["/Coul" & "/Znss"] = "Background: &HFAFAFA&; "
    Settings["/Coul" & "/Znaff"] = "Background: &HEEEEEE&; "
    Settings["/Coul" & "/Focus"] = "Background: &HF9FFC7&; "
    Settings["/Coul" & "/Coulfonds"] = "Background: &FFEE81&; "
    Settings["/Coul" & "/Others"] = "Background: &FFE0B8&; "
    Settings["/Coul" & "/Fcs"] = "Background: &HF9FFC7&"
    Settings["/Coul" & "/Stk"] = "Background: &HCFF58E&; Font: serif,9; "
    Settings["/Coul" & "/Coulfonds"] = "255;252;216;"
    Settings["/Coul" & "/Others"] = "255;232;199;"
    Settings["/Coul" & "/Facts"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Avs"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Bl"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Devis"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Devis2"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Cmde"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Prf"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Nstk"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Eps"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Spd"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Motps"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Momnt"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings.save
    Settings.Reload
  Endif
  If Not Exist(User.home & "/tmp") Then Mkdir User.home & "/tmp"
  Application.Font = Font["Serif,11"]
  Try Fontes = Settings["/Soc" & Societe & "/Font"]
  If IsNull(fontes) Then
    Application.Font = Font["Serif,11"]
  Else
    Application.Font = Font[Fontes]
  Endif
  
  Utils.glb()
  Utils.db.Open
  If Not IsNull(Utils.db.Login) Then Shell "mysql -h " & Settings["/dbase/Host"] & " " & " -u " & Utils.db.Login & " -p" & Utils.db.Password & " -e \"use " & Utils.db.Name & ";" & "SET @@global.sql_mode=NO_ENGINE_SUBSTITUTION " & "; \"" Wait
  FMain.Main

End

Public Sub Coul()

  Dim Fonds As String

  Try Fonds = Settings["/Coul/Others"]
  If Not Error Then
    If Not IsNull(Fonds) Then
      lig2 = Split(Fonds, ";")
      Try R = Lig2[0]
      Try G = Lig2[1]
      Try B = Lig2[2]
      If Error Then
        R2 = 229
        G2 = 233
        B2 = 255
      Endif
    Endif
  Endif
  Try Fonds = Settings["/Coul/Coulfonds"]
  If Not Error Then
    If Not IsNull(Fonds) Then
      lig2 = Split(Fonds, ";")
      Try R2 = Lig2[0]
      Try G2 = lig2[1]
      Try B2 = lig2[2]
      If Error Then
        R2 = 255
        G2 = 254
        B2 = 212
      Endif
    Endif
  Endif

End

Public Sub Verif_Maj()

  Dim version As String
  Dim txt As String
  Dim $hform As Form
  Dim hLabel As Label

  $hForm = New Form As "Form"
  $hform.Width = 600
  $hform.Height = 400
  $hForm.Border = Border.Etched
  $hform.Title = "Mise à jour de Laurux"
  hLabel = New Label($hForm)
  hLabel.Text = "La mise à jour prend un peu de temps.\n Veuillez patienter SVP."
  hLabel.Width = 600
  hLabel.Alignment = Align.center
  hLabel.Height = 40
  hLabel.Y = 12
  'hLabel.Border = Border.Plain
  hlb = New Label($hForm)
  hlb.Width = 600
  hlb.Height = 20
  hlb.Y = 70
  hlb.Alignment = Align.center
  hpb = New ProgressBar($hForm)
  hpb.Width = 400
  hpb.Height = 20
  hpb.X = 100
  hpb.Y = 100
  $hForm.Move($hForm.ScreenX, $hForm.ScreenY, 600, 200)
  $hform.Center
  Version = Settings["/dbase/Version"]
  If Exist(User.Home & "/tmp/pb1.txt") Then Kill User.Home & "/tmp/pb1.txt"
  If Exist("/version.txt") Then Kill "/version.txt"
  If Exist("/Laurux3.tar.gz") Then Kill "/Laurux3.tar.gz"
  If Exist(User.Home & "/tmp/ping.txt") Then Kill User.Home & "/tmp/ping.txt"
  Shell "ping -c 1 www.laurux.fr >" & User.Home & "/tmp/ping.txt 2>&1" Wait
  If Exist(User.Home & "/tmp/ping.txt") Then
    txt = Trim$(File.Load(User.Home & "/tmp/ping.txt"))
  Endif
  If InStr(txt, "cpanel1") <> 0 Then
    Shell "wget -q" & " " & "http://www.laurux.fr/file/version.txt" & " -P " & User.Home & "/tmp" Wait
    If Exist(User.Home & "/tmp/version.txt") Then
      txt = Trim$(File.Load(User.Home & "/tmp/version.txt"))
      If IsNull(Version) And Not IsNull(txt) Or If Not IsNull(Right$(version, 4)) And Not IsNull(txt) Then
        If Replace$(Right$(txt, 4), ",", ".") > Replace$(Right$(version, 4), ",", ".") Then
          If Message.Question("Attention ! Vous allez mettre à jour votre logiciel Laurux\n Vous devez être connecté au réseau internet. \n Etes-vous d'accord ?", "Oui", "Non") = "1" Then
            Try Move Application.Path & "/Laurux3.gambas" To Application.Path & "/Laurux3.old.gambas"
            Shell "cd " & User.Home
            $hForm.Show
            Wait 1
            $hform.Mouse = Mouse.Wait
            Shell "wget http://www.laurux.fr/file/Laurux3.tar.gz -P " & User.Home & " -o " & User.Home & "/tmp/pb1.txt"
            Avancement()
            Shell "cd " & User.Home & " " & "; tar xvfz " & User.Home & "/Laurux3.tar.gz" Wait
            Wait 1
            Kill User.Home & "/Laurux3.tar.gz"
            Kill User.Home & "/tmp/version.txt"
            $hform.Mouse = Mouse.Default
            $hform.Close
            Settings["/Affmaj"] = 1
            Settings["/dbase/Version"] = Txt
            Settings.Save
            Message.Warning("Mise à jour terminée ! Veuillez relancer Laurux SVP !")
            Quit
          Endif
        Endif
      Endif
    Else
      $hform.Mouse = Mouse.Default
      Message.Warning("Problème de mise à jour! Veuillez vérifier votre connexion SVP.")
    Endif
  Else
    $hform.Mouse = Mouse.Default
    Message.Warning("Problème de mise à jour! Veuillez vérifier votre connexion SVP.")
  Endif
Catch
  Music.Load(Start.Musique)
  Music.Play
  message.Error(Error.Text & " " & Error.where)

End

Public Sub Avancement()

  Dim hFile As File
  Dim chaine As String
  Dim v As Integer
  Dim numligne As Integer
  Dim L3 As String = "0"

  numligne = 0
  v = 0
  Do While Not Exist(User.Home & "/tmp/pb1.txt")  'On test l'existence du fichier temporaire
  Loop
  Wait 0.1
  Do While L3 <> "100"      'On test la fin du téléchargement
    hFile = Open User.Home & "/tmp/pb1.txt" For Input
    numligne = 0
    While Not Eof(hFile)
      Line Input #hFile, chaine
      If v = 100 Then L3 = "100"
      If Mid(chaine, 7, 2) = "K " And Len(chaine) <= 78 And Len(chaine) >= 75 Then
        L3 = Mid(chaine, 63, 3)
        If CInt(L3) > v Then  'On incrémente la barre de progression
          v = CInt(L3)
          Hpb.Value = CInt(L3) / 100
          hlb.Text = Chaine
        Endif
      Else
        Wait
      Endif
    Wend
    Close #hFile
  Loop
  'CLOSE #hFile
  Try Kill User.Home & "/tmp/pb1.txt"  '--- Suppression du fichier temporaire ---

End

